name = "gleam_msgpack"
version = "0.1.0"
licences = ["Apache-2.0"]
description = "MessagePack protocol in pure Gleam"
repository = { type = "github", user = "seep", repo = "gleam_msgpack" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.21"
gleam_bitwise = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 0.6"
